### ISSUE TITLE
Ringraziamenti all'ateneo per il finanziamento

### ISSUE THREAD

**Issue by 25sal** [25sal/cleopatrawebsite#5]
Dobbiamo aggiungere queta frase.

The Cleopatra Project has been funded by the University of Campania "Luigi
Vanvitelli" through the VALERE 2019 research program.

Dove la mettiamo? Nel Footer? Un banner?

**Comment by ambrix** [comment]
L'ho inserito sopra il footer ... fatemi sapere se va bene così

**Comment by 25sal** [comment]
Va bene
